name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, zip

    - name: Install composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"

    - name: Install dependencies
      run: php composer.phar install --no-dev

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: minedocs
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_415ECACFDCE94B20BAFC40714B12BF4D }}
        package: .
